### PR TITLE
specs passing using ROM's master

### PR DESCRIPTION
**Pull request by nando**
i don't know if something more needs to be done in order to be considered "bumped" to 0.9. If that's the case, please tell me what should i do.

p.d. @solnic nice talk at the Baruco, thanks!!!

### CODE REVIEW

**Comment by nando** [comment]
sorry for not creating a branch for this :(

**Comment by maetl** [comment]
> sorry for not creating a branch for this :(

That’s okay. The change looks good, thanks very much for that!

I’ll test this tomorrow and merge it in at that stage if I don’t see any major problems then.

**Comment by maetl** [comment]
As far as bumping the version goes, I’m not sure what to do about versioning this in a compatible way with the main gem (@solnic might be able to suggest something here).

I’d prefer not to go straight to `0.9` until we look at completing several missing features first (not sure if I’ve written this down anywhere yet):

- Add separate commands for `Edge` and `Node` operations (`Create`, `Update`, `Delete` for starters).
- Add graph migration support using the create/update DSL from the `neo4j-cypher` Gem
- Embed the `neo4j-cypher` query DSL in the `ROM::Neo4j::Relation` (fluent interface will add a lot of value to the API)
- Fix the issues with prefix mapping in `ROM::Mapper` from various common `return` styles from Neo4j graph traversals
- Support embedded mode (JRuby only)

**Comment by nando** [comment]
Thanks for making us that list of missing features. Since i'm a complete ROM's newbie they give me a bunch of nice challenges to keep learning it in the context of Neo4j.

Would you like me to split them in five new issues in order to keep track of their evolution? Or do you prefer to keep talking about them in other place?

**Comment by solnic** [comment]
What's the concern wrt versioning? You could just bump minor version.

@nando re talk, my pleasure :)

**Comment by maetl** [comment]
> What's the concern wrt versioning? You could just bump minor version.

I don’t think there’s a concern, I think the original question was along the lines of “why doesn’t this lib track the minor version of the other ROM libs?” Apologies if I misinterpreted.

My intention would be to keep bumping the minor versions independently of other adapters, until it reaches a state where we consider it feature complete. Please let me know if there is a better way :)

**Comment by maetl** [comment]
Ah, actually I may have misinterpreted more than that. Was “bumping” in the context of the **dependency** on 0.9.1, not this Gem version itself.

Yes — this Gem needs to be moved up to ROM 0.9.1 based on these changes. We should also look at bumping the Neo4j dependency to 5.1.

**Comment by maetl** [comment]
:+1:

Looks good. I’ll sort out the dependencies in the gemspec separately.

**Comment by maetl** [comment]
Thank you very much @nando, your change is now live and published to Rubygems: https://rubygems.org/gems/rom-neo4j

:cake:

**Comment by nando** [comment]
You're very welcome @maetl, and thanks for releasing the 0.2 gem!!!

It's great for me to see that my work can be helpful even with my current lack of ROM-RB knowledge :)

**Pull request merged**
